#ifndef CONSTANTES_H
#define CONSTANTES_H

const int TAILLE_TORPILLEUR = 2;
const int TAILLE_CONTRE_TORPILLEUR = 3;
const int TAILLE_SOUS_MARIN = 3;
const int TAILLE_CROISEUR = 4;
const int TAILLE_PORTE_AVION = 5;

const int TAILLE_BATEAUX[] = { 0, TAILLE_TORPILLEUR, TAILLE_SOUS_MARIN, TAILLE_CONTRE_TORPILLEUR, TAILLE_CROISEUR, TAILLE_PORTE_AVION };
const int NB_BATEAU = 5;

const int HORIZONTAL = 0;
const int VERTICAL = 1;

#endif
